// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class keepPhoneNumberRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keepPhoneNumberRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202101280024261_keepPhoneNumberRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
